--comment
--How to work with PeopleID if doctor vs office
CREATE DATABASE APPTMANAGER;
USE APPTMANAGER;

CREATE TABLE Persons ( 
  PeopleID
  FirstName
  LastName
  Type  
  CONSTRAINT PERSONS_PK PRIMARY KEY (PeopleID)
  ); 
  
CREATE TABLE Patients (
  PatientID
  FirstName
  LastName
  DateOfBirth  
  CONSTRAINT PATIENTS_PK PRIMARY KEY (PatientID),
  CONSTRAINT PEOPLE_PATIENTS_FK FOREIGN KEY (PatientID) REFERENCES People (PeopleID)
  );
  
CREATE TABLE Doctors ( 
  DoctorID
  DocName
  OfficeName
  Specialization
  Comments
  Address1
  Address2
  City
  Province
  PostalCode
  Phone
  Email
  Fax  
  CONSTRAINT DOCTORS_PK PRIMARY KEY (DoctorID),
  CONSTRAINT PEOPLE_DOCTORS_FK FOREIGN KEY (DoctorID) REFERENCES People (PeopleID)
  ); 
  
CREATE TABLE Medications ( 
  MedID
  MedName  
  CONSTRAINT MEDICATIONS_PK PRIMARY KEY (MedID)
  ); 
  
CREATE TABLE Issues (
  IssueID
  PatientID
  IssueTitle
  IssueText   
  CONSTRAINT ISSUES_PK PRIMARY KEY (IssueID),
  CONSTRAINT PATIENTS_ISSUES_FK FOREIGN KEY (PatientID) REFERENCES Patients (PatientID)
  );
  
CREATE TABLE Appointments ( 
  ApptID
  PatientID
  DoctorID
  DateAndTime
  Comments
  CONSTRAINT APPOINTMENTS_PK PRIMARY KEY (ApptID),
  CONSTRAINT PATIENTS_APPOINTMENTS_FK FOREIGN KEY (PatientID) REFERENCES Patients (PatientID),
  CONSTRAINT DOCTORS_APPOINTMENTS_FK FOREIGN KEY (DoctorID) REFERENCES Doctors (DoctorID)
  ); 
  
CREATE TABLE Actions ( 
  ActionID
  ApptID
  ActionText
  CONSTRAINT ACTIONS_PK PRIMARY KEY (ActionID),
  CONSTRAINT APPOINTMENTS_ACTIONS_FK FOREIGN KEY (ApptID) REFERENCES Appointments (ApptID)
  ); 
  
CREATE TABLE PeopleActions (
  PeopleID
  ActionID
  CONSTRAINT PEOPLE_PA_PK PRIMARY KEY (PeopleID),
  CONSTRAINT ACTIONS_PA_PK PRIMARY KEY (ActionID),
  CONSTRAINT PEOPLE_PA_FK FOREIGN KEY (PeopleID) REFERENCES People (PeopleID),
  CONSTRAINT ACTIONS_PA_PK FOREIGN KEY (ActionID) REFERENCES Actions (ActionID)
  );
  
CREATE TABLE PatientsMeds ( 
  PatientID
  MedID
  Dosage
  Instructions
  CONSTRAINT PATIENTS_PM_PK PRIMARY KEY (PatientID),
  CONSTRAINT MEDS_PM_PK PRIMARY KEY (MedID),
  CONSTRAINT PATIENTS_PM_FK FOREIGN KEY (PatientID) REFERENCES Patients (PatientID),
  CONSTRAINT MEDS_PM_FK FOREIGN KEY (MedID) REFERENCES Medications (MedID)
  ); 
  
CREATE TABLE ApptsIssues (
  ApptID
  IssueID
  CONSTRAINT APPTS_AI_PK PRIMARY KEY (ApptID),
  CONSTRAINT ISSUES_AI_PK PRIMARY KEY (IssueID),
  CONSTRAINT APPTS_AI_FK FOREIGN KEY (ApptID) REFERENCES Appointments (ApptID),
  CONSTRAINT ISSUES_AI_FK FOREIGN KEY (IssueID) REFERENCES Issues (ApptID)
  );

